pip3 install numpy
pip3 install scipy
pip3 install scikit-learn
pip3 install matplotlib
pip3 install mglearn
pip3 install pandas
pip3 install pillow
pip3 install graphviz
pip3 install python-graphviz
pip3 install imageio
pip3 install joblib
pip3 install jupyter
pip3 install jupyterlab